name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: Dashboard/package-lock.json

      - name: Install dependencies
        working-directory: Dashboard
        run: npm ci

      - name: Build
        working-directory: Dashboard
        env:
          VITE_BASE: /Frontend/
          # Optionally set VITE_API_BASE via repository Variables/Secrets to point to an HTTPS proxy (e.g., https://<user>.github.io/Frontend/api)
          # VITE_API_BASE: ${{ vars.VITE_API_BASE }}
        run: npm run build

      - name: Create SPA 404.html
        working-directory: Dashboard/dist
        run: cp index.html 404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: Dashboard/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
